import { readable, writable, type Writable } from 'svelte/store'
import type { Readable } from 'svelte/motion'
import type { NegociationBackend } from '@/libs/negociationTypes'

export const negociation: Writable<NegociationBackend> = writable({
	customerName: '',
	status: '',
	startingDate: '',
	condition: '',
	inflow: '',
	billingDate: '',
	scheduledDeposit: '後払い',
	outcome: '',
	nextContactDate: '',
	nextContactTime: '',
	lastContact: '',
	postalCode: '',
	prefecture: '',
	city: '',
	address1: '',
	address2: '',
	numberOfBeds: 0,
	estimate: [],
	personInCharge: '',
	responsiblePerson: '',
	memo: [],
	dm: '',
	video: '',
	negociationId: 0,
	custCd: 0,
	checkboxes: [
		{ title: '動画視聴　依頼', isChecked: false },
		{ title: '動画視聴　確認', isChecked: false },
		{ title: '新品　購入経験', isChecked: false },
		{ title: '増台提案', isChecked: false },
		{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
		{
			title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
			isChecked: false
		},
		{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
		{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
		{ title: '前払い（特別値引き）の説明', isChecked: false },
		{ title: '中古　購入経験', isChecked: false }
	],
	bottleneck: '',
	occasion: '',
	risk: '',
	outcomeHistory: [],
	communication: '',
	distanceKm: 0,
	distanceTime: 0,
	preference: '',
	contact: '',
	billingEstimation: 0
})

export const negociations: Writable<NegociationBackend[]> = writable([
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2002-01-01',
		condition: 'A',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		scheduledDeposit: '前払い',
		outcome: '2023-05-30',
		nextContactDate: '2023-05-30',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '1-1-1',
		numberOfBeds: 1,
		billingEstimation: 260000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 1,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: true },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: true
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: 'test',
		occasion: 'test',
		risk: 'test',
		outcomeHistory: [{ date: '2023-05-30', memo: 'テスト' }],
		communication: '新規依頼',
		distanceKm: 2,
		distanceTime: 3,
		preference: '新品',
		contact: '',
		estimate: [
			{
				issueDate: '2023-02-14',
				dueDate: '2023-10-23',
				estimateWithoutTax: 130000,
				estimateTax: 1300,
				items: [{ name: 'item', quantity: 20, price: 650 }],
				withTax: true
			},
			{
				issueDate: '2023-02-14',
				dueDate: '2023-10-23',
				estimateWithoutTax: 130000,
				estimateTax: 1300,
				items: [{ name: 'item', quantity: 20, price: 650 }],
				withTax: true
			}
		],
		responsiblePerson: '中田',
		register_by: 2,
		register_at: '2023-11-25T16:09:16.703949+09:00',
		update_by: 2,
		update_at: '2023-11-25T16:11:28.266800+09:00',
		delete_by: null,
		delete_at: '2023-11-25T16:09:16.703988+09:00'
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'B',
		inflow: '新規FAX',
		billingDate: '',
		outcome: '',
		nextContactDate: '2023-05-30',
		nextContactTime: '',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 2,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [
			{
				issueDate: '2023-02-14',
				dueDate: '2023-10-23',
				estimateWithoutTax: 130000,
				estimateTax: 1300,
				items: [{ name: 'item', quantity: 20, price: 650 }],
				withTax: true
			},
			{
				issueDate: '2023-02-14',
				dueDate: '2023-10-23',
				estimateWithoutTax: 3250,
				estimateTax: 1300,
				items: [{ name: 'item', quantity: 5, price: 650 }],
				withTax: true
			},
			{
				issueDate: '2023-02-14',
				dueDate: '2023-10-23',
				estimateWithoutTax: 650000,
				estimateTax: 0,
				items: [{ name: 'item', quantity: 100, price: 650 }],
				withTax: true
			}
		],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 yyyyyyy 緑風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'A',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 3,
		custCd: 2,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'B',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '',
		nextContactTime: '',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 4,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'A',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '2023-05-30',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 5,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'B',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '2023-05-30',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 6,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'A',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '2023-05-30',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 7,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'B',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '2023-05-30',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 8,
		custCd: 3,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'A',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '2023-05-30',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 9,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'B',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '2023-05-30',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 10,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'A',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '2023-05-30',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 11,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	},
	{
		customerName: '社会営利法人 xxxxxxx 赤風荘',
		status: '受注',
		startingDate: '2023-01-01',
		condition: 'B',
		inflow: '新規FAX',
		billingDate: '2023-06-30',
		outcome: '2023-05-30',
		nextContactDate: '2023-05-30',
		nextContactTime: '13:00',
		lastContact: '2023-05-30',
		postalCode: '6040944',
		prefecture: '京都府',
		city: '京都市中京区',
		address1: '橘町押小路通御幸町西入',
		address2: '',
		numberOfBeds: 1,
		billingEstimation: 130000,
		personInCharge: '山田太郎',
		memo: [{ date: '2023-05-30', memo: 'KA-9800　83Ｒセンターロック' }],
		dm: '郵送済み',
		video: '2023-05-30',
		negociationId: 12,
		custCd: 1,
		checkboxes: [
			{ title: '動画視聴　依頼', isChecked: false },
			{ title: '動画視聴　確認', isChecked: false },
			{ title: '新品　購入経験', isChecked: false },
			{ title: '増台提案', isChecked: false },
			{ title: '値上げ：全世界の値上げ傾向。物流・保管・電気等の徹底', isChecked: false },
			{
				title: '傷、色あせ：中古商材の為、多少の傷や色あせ有り。洗浄・メンテの徹底',
				isChecked: false
			},
			{ title: '商品確保：中古商材の為、購入契約者優先の商品確保', isChecked: false },
			{ title: '締め支払い：契約書締結による締め支払い', isChecked: false },
			{ title: '前払い（特別値引き）の説明', isChecked: false },
			{ title: '中古　購入経験', isChecked: false }
		],
		bottleneck: '',
		occasion: '',
		risk: '',
		outcomeHistory: [],
		scheduledDeposit: '後払い',
		communication: '',
		distanceKm: 0,
		distanceTime: 0,
		preference: '',
		contact: '',
		estimate: [],
		responsiblePerson: ''
	}
])
